### ISSUE TITLE
Error when export contains attributes with illegal XML characters

### ISSUE THREAD

**Issue by ATran31** [ptarroso/layer2kmz#10]
When export includes an attribute field with the characters `"` `>`  `<` or `&` it will cause an error. This can probably be handled properly escaping those characters i.e.
 `&` becomes `&amp;`
`<` becomes `&lt;`
`>` becomes `&gt;`
`"` becomes `&quot;`

**Comment by ptarroso** [comment]
Yes, those characters are not well handled in the code... I'll try to adapt the code to escape correctly the text in the next version.

**Comment by ptarroso** [comment]
@ATran31 I have managed to change the code to allow escaped characters. The plugin is not yet on the qgis repository but the last version here in github already has the changes. The problem was that the table associated with each place mark is a cdata element that could not be escaped and was not properly handled in the python native xml.ElementTree. I think I found a workaround that works!

**Comment by ATran31** [comment]
I just installed the latest version and tested against some datasets. I am getting a `Error: maximum recursion depth exceeded in comparison` when exporting.

**Comment by ptarroso** [comment]
I get that error sometimes, especially when I'm reloading the plugin in qgis (with reload plugin) ... I couldn't t find the source of error in the code. I'm not using recursion anywhere. I suspect that is something that qgis triggers when loading the plugin. However, after restarting qgis it works flawlessly with exactly the same input.

**Comment by ATran31** [comment]
I restarted QGIS and everything works perfectly. Thanks @ptarroso for the quick fix and continued support of the plugin!
