### ISSUE TITLE
Export is only correct when layer's SRC is in geographic system, wgs84, decimal degrees

### ISSUE THREAD

**Issue by mcunha84** [ptarroso/layer2kmz#11]
Hello,
If my layer is imported with another SRC (example UTM), even if my project is in geographic coordinates, the generated KMZ will not plot correctly the shapes. It reads directly the coordinates from the source file (UTM) instead of project's SRC, and doesn't do the conversion.
If I input the file with geographic coordinates, the module works like a charm!

My suggestion, you can read the coordinates from the input file, but it has to read its SRC and, if necessary, while writing the kml, convert the coordinates.
sample code from KML inside KMZ, with unconverted coordinates:
``        <Folder id="B005 - YBL">
            <name>B005 - YBL</name>
            <Placemark>
                <name>B005 - YBL</name>
                <styleUrl>#feito</styleUrl>
                <ExtendedData>
                    <SchemaData schemaUrl="#20191210_MEA_SEV_torres_01052020">
                        <SimpleData name="Adquirido">Feito</SimpleData>
                    </SchemaData>
                </ExtendedData>
                <Point>
                    <coordinates>311282.84,8994848.74</coordinates>
                </Point>
            </Placemark>
        </Folder>``

**Comment by ptarroso** [comment]
Hi! Thanks for the feedback.

In fact, that was a design option. The purpose of the plugin was format conversion only, not coordinate transformation. I did not want to have some CRS transformation in the background, and left that responsibility to the user. I imagine that most users are converting to kmz to use in the GEarth, but other programs can be used and other CRS might be needed. If conversion was done in the background, then it would limit that use.

Having said that, I see that your issue is when layer and project CRS mismatch. Maybe I can add a tick mark to the GUI allowing transformation when that mismatch is found. But, as this can be easily solved by the user, it is nor a priority.
